### ISSUE TITLE
CI: Clean up old container images workflow fails

### ISSUE THREAD

**Issue by hfrSchmidt** [IKIM-Essen/EMCP-slurm#2]

**Comment by enasca** [comment]
Can you check if this repo has access to `secrets.PAT_HFRSCHMIDT`?

**Comment by enasca** [comment]
This is where the code reads the token: https://github.com/snok/container-retention-policy/blob/f617f1ca161a52bce48417eedd76924e71d0b4d9/main.py#L512

It seems that we're getting an empty string.

**Comment by hfrSchmidt** [comment]
Yes that was indeed the problem. Somehow the repository secret was deleted.
